export const AI_PROFILES = {
    BALANCED: { name: 'Balanced', scoutCap: 2, salvagerCap: 1, transportRatio: 3, minCombatForTransport: 2, fleetSize: 3, aggressiveness: 0.5, retreatThreshold: 0.5, engageThreshold: 1.1, expansionBias: 0.5, researchPriority: 0.5, shipPreference: ['Cruiser', 'Destroyer', 'Frigate', 'Fighter'], repairStrategy: 'VALUE' },
    AGGRESSIVE: { name: 'Aggressive', scoutCap: 1, salvagerCap: 0, transportRatio: 5, minCombatForTransport: 2, fleetSize: 4, aggressiveness: 0.9, retreatThreshold: 0.3, engageThreshold: 0.8, expansionBias: 0.35, researchPriority: 0.3, shipPreference: ['Cruiser', 'Destroyer', 'Fighter'], repairStrategy: 'SPEED' },
    DEFENSIVE: { name: 'Defensive', scoutCap: 2, salvagerCap: 1, transportRatio: 4, minCombatForTransport: 3, fleetSize: 5, aggressiveness: 0.2, retreatThreshold: 0.7, engageThreshold: 1.5, expansionBias: 0.4, researchPriority: 0.6, shipPreference: ['Cruiser', 'Frigate', 'Destroyer', 'Fighter'], repairStrategy: 'CRITICAL' },
    EXPANDER: { name: 'Expander', scoutCap: 2, salvagerCap: 1, transportRatio: 2, minCombatForTransport: 1, fleetSize: 2, aggressiveness: 0.4, retreatThreshold: 0.5, engageThreshold: 1.2, expansionBias: 0.8, researchPriority: 0.4, shipPreference: ['Destroyer', 'Fighter', 'TroopTransport'] },
    TECHNOLOGIST: { name: 'Technologist', scoutCap: 2, salvagerCap: 1, transportRatio: 3, minCombatForTransport: 1, fleetSize: 3, aggressiveness: 0.3, retreatThreshold: 0.6, engageThreshold: 1.2, expansionBias: 0.5, researchPriority: 0.9, shipPreference: ['Cruiser', 'Destroyer', 'Frigate'] },
    ECONOMIST: { name: 'Economist', scoutCap: 2, salvagerCap: 2, transportRatio: 3, minCombatForTransport: 1, fleetSize: 3, aggressiveness: 0.4, retreatThreshold: 0.6, engageThreshold: 1.3, expansionBias: 0.6, researchPriority: 0.5, shipPreference: ['Destroyer', 'Fighter'] },
    SWARM: { name: 'Swarm', scoutCap: 3, salvagerCap: 2, transportRatio: 4, minCombatForTransport: 3, fleetSize: 6, aggressiveness: 0.8, retreatThreshold: 0.2, engageThreshold: 0.6, expansionBias: 0.3, researchPriority: 0.2, shipPreference: ['Cruiser', 'Fighter'] },
    CAPITALIST: { name: 'Capitalist', scoutCap: 1, salvagerCap: 1, transportRatio: 3, minCombatForTransport: 1, fleetSize: 2, aggressiveness: 0.6, retreatThreshold: 0.6, engageThreshold: 1.2, expansionBias: 0.5, researchPriority: 0.6, shipPreference: ['Cruiser', 'Destroyer', 'Frigate'] },
    PIRATE: { name: 'Raider', scoutCap: 0, salvagerCap: 0, transportRatio: 99, minCombatForTransport: 99, fleetSize: 3, aggressiveness: 1.0, retreatThreshold: 0.1, engageThreshold: 0.5, expansionBias: 0.0, researchPriority: 0.0, shipPreference: ['Fighter', 'Frigate'], repairStrategy: 'SPEED' }
};
